### ISSUE TITLE
新着チャンネル通知が欲しい

### ISSUE THREAD

**Issue by pocke** [ruby-jp/ruboty-ruby-jp#25]

**Comment by sanfrecce-osaka** [comment]
これは `ruboty-cron` で決まった時間に流す想定ですか？ 👀

**Comment by pocke** [comment]
> これは ruboty-cron で決まった時間に流す想定ですか？ 


そう実装するのが良いかなーと思います！
Slack側から新規チャンネル作成が通知されてくる仕組みがあればそれに乗っかることもできそうですが、まあcronで見たほうが実装は楽かなと言う気がします
